name: todays_activities
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.15
  intl: ^0.19.0
  provider: ^6.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
